[project]
name = "texas-oil-data-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.5.5",
    "google-cloud-bigquery>=3.42.3",
    "google-cloud-storage>=3.13.0",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.2",
    "pandas>=2.3.3",
    "pandera>=0.32.1",
    "pyarrow>=25.0.0",
    "pydantic-settings>=2.15.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
